/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("running train booking system");
        Scanner sc = new Scanner(System.in);   //needed to take input
    }
}
